### PR TITLE
Fix typos in conats for cheap

### PR DESCRIPTION
**Pull request by jonsterling**
grammar, punctuation, etc.

### CODE REVIEW

**Comment by jozefg** [comment]
Ah this is wonderful! Thank you so much.

**Comment by jozefg** [comment]
Published it over [here](http://jozefg.bitbucket.org/posts/2015-07-17-conats-for-cheap.html).

**Comment by jonsterling** [comment]
no problem! Might be useful to also add a link to get JonPRL.

**Comment by jozefg** [comment]
Oh good call, added :)

**Pull request merged**
